# Generated by Django 5.2.16 on 2026-07-25 16:03

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingblock_bookinghistory_bookingserviceitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='treatment_photo',
            field=models.ImageField(blank=True, upload_to=bookings.models.booking_intake_path),
        ),
    ]
