# Generated by Django 5.2.16 on 2026-08-21 01:21

import bookings.models
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_treatment_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='treatment_photo',
            field=models.ImageField(blank=True, storage=core.storage.private_media_storage, upload_to=bookings.models.booking_intake_path),
        ),
    ]
