# Generated by Django 5.2.16 on 2026-08-21 01:21

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_customercartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, storage=core.storage.public_media_storage, upload_to='products/%Y/%m/'),
        ),
    ]
