# Generated by Django 5.2.16 on 2026-07-21 02:00

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_branch_secondary_telephone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price_type', models.CharField(choices=[('fixed', 'Fixed price'), ('starting_from', 'Starting from'), ('range', 'Price range'), ('options', 'Price options'), ('quotation', 'Manual quotation')], default='fixed', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('maximum_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pricing_notes', models.CharField(blank=True, max_length=300)),
                ('duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('is_clinic_service', models.BooleanField(default=True)),
                ('is_home_service', models.BooleanField(default=False)),
                ('requires_full_payment', models.BooleanField(default=True)),
                ('allows_pay_at_clinic', models.BooleanField(default=True)),
                ('is_consultation', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['category__display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'service categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBranchAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_availability', to='branches.branch')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_availability', to='services.service')),
            ],
            options={
                'ordering': ['branch__name', 'service__name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='branches',
            field=models.ManyToManyField(related_name='services', through='services.ServiceBranchAvailability', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory'),
        ),
        migrations.AddConstraint(
            model_name='servicebranchavailability',
            constraint=models.UniqueConstraint(fields=('service', 'branch'), name='unique_service_branch_availability'),
        ),
    ]
