# Generated by Django 5.2.16 on 2026-08-11 23:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=80)),
                ('address_type', models.CharField(choices=[('billing', 'Billing'), ('delivery', 'Delivery'), ('both', 'Billing and delivery')], default='delivery', max_length=20)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('address_line_1', models.CharField(max_length=250)),
                ('address_line_2', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(max_length=120)),
                ('region', models.CharField(max_length=120)),
                ('landmark', models.CharField(blank=True, max_length=250)),
                ('country', models.CharField(default='Ghana', max_length=80)),
                ('is_default_billing', models.BooleanField(default=False)),
                ('is_default_delivery', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default_delivery', '-is_default_billing', 'label'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default_billing', True)), fields=('customer',), name='one_default_billing_address_per_customer'), models.UniqueConstraint(condition=models.Q(('is_default_delivery', True)), fields=('customer',), name='one_default_delivery_address_per_customer')],
            },
        ),
    ]
