# Generated by Django 5.2.16 on 2026-08-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerconsent',
            name='photograph_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerconsent',
            name='photograph_consent_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
