# Generated by Django 5.2.16 on 2026-07-21 00:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Use uppercase letters, numbers, hyphens, or underscores.', regex='^[A-Z0-9_-]+$')])),
                ('address', models.TextField()),
                ('telephone_number', models.CharField(max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('google_maps_url', models.URLField(blank=True)),
                ('opening_days', models.JSONField(default=list)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'branches',
                'ordering': ['name'],
            },
        ),
    ]
