# Generated by Django 5.2.16 on 2026-07-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='secondary_telephone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='branch',
            name='secondary_whatsapp_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
