# Generated by Django 5.2.16 on 2026-07-21 00:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_role', models.CharField(blank=True, max_length=100)),
                ('action', models.CharField(max_length=150)),
                ('record_type', models.CharField(max_length=150)),
                ('record_id', models.CharField(max_length=255)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_identifier', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='branches.branch')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['record_type', 'record_id'], name='auditlog_au_record__f1a892_idx'), models.Index(fields=['branch', 'created_at'], name='auditlog_au_branch__e95c85_idx'), models.Index(fields=['actor', 'created_at'], name='auditlog_au_actor_i_e7d961_idx'), models.Index(fields=['action', 'created_at'], name='auditlog_au_action_403129_idx')],
            },
        ),
    ]
