# Generated by Django 5.2.16 on 2026-08-09 02:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import payments.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_treatment_photo'),
        ('branches', '0004_normalize_existing_contact_numbers'),
        ('orders', '0002_orderitem_stockreservation_order_cancelled_at_and_more'),
        ('payments', '0002_payment_receipt_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=payments.models.invoice_reference, editable=False, max_length=24, unique=True)),
                ('source_type', models.CharField(max_length=20)),
                ('source_reference', models.CharField(max_length=24)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('line_items', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('void', 'Void'), ('expired', 'Expired')], default='open', max_length=20)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='bookings.booking')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='branches.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders.order')),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['customer', 'status', 'issued_at'], name='payments_in_custome_64d4e2_idx'), models.Index(fields=['branch', 'status', 'issued_at'], name='payments_in_branch__c8b74f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', False), ('order__isnull', True)), models.Q(('booking__isnull', True), ('order__isnull', False)), _connector='OR'), name='invoice_has_exactly_one_source')],
            },
        ),
    ]
