# Generated by Django 5.2.16 on 2026-08-21 01:21

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, storage=core.storage.public_media_storage, upload_to='gallery/%Y/%m/'),
        ),
    ]
